# Generated by Django 6.1.1 on 2026-10-06 06:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_usergoal"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usergoal",
            name="goal",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(30),
                    django.core.validators.MaxValueValidator(720),
                ]
            ),
        ),
    ]
